content_path: content
template_path: templates
template_static_path: template_assets
filter_paths:
    - dactyl/
    - custom_filters/
    - more_custom_filters/
filters:
    - custom_filters
    - more_custom_filters
    - include_url
    - include_code
    - badges
    - patriots
    - buttonize
    - multicode_tabs
    - xrefs

targets:
    -   name: everything
        display_name: Dactyl Examples
        filters:
            - add_version
            - badges
            - buttonize
            - callouts
            - demote_headers
            - include_url
            - link_replacement
            - multicode_tabs
            - xrefs
        demote_headers_pdf_only: true
        #stylesheet: template_assets/dactyl.css
        foo: "fooooooo"

    -   name: filterdemos
        display_name: Target with just the filter example pages
    

    -   name: conditionals
        display_name: Conditional Text Target
        condition: tests-2

pages:
   # -   name: All Filters
   #     html: all-filters.html
   #     category: Filter Demos 
   #     section_header: true
   #     parent: filters-index.html
   #     template: landing.html
   #     targets:
   #         - filterdemos
   #         - everything
    
    -   name: Tests
        html: tests-index.html
        category: Tests
        section_header: true
        template: landing.html
        targets:
            - everything

    -   md: includes.md
        #category: Tests
        parent: tests-index.html
        #sidebar: left_only
        targets:
            - everything

    -   md: with-frontmatter.md
        html: with-frontmatter.html
        parent: tests-index.html
        sidebar: right_only
        targets:
            - everything

    -   md: cli-vars.md
        html: cli-vars.html
        parent: tests-index.html
        targets:
            - everything

    -   name: Conditionals Test
        category: Tests
        md: conditionals.md
        parent: tests-index.html
        targets:
            - everything
            - conditionals

    -   name: Lists and Code Blocks Demo
        category: Tests
        md: lists-and-codeblocks.md
        parent: tests-index.html
        targets:
            - everything

    -   name: GitHub Markdown Compatibility
        category: Tests
        md: gfm-compat.md
        parent: tests-index.html
        targets:
            - everything

    -   md: header_stress_test.md
        category: Tests
        parent: tests-index.html
        targets:
            - everything

    -   md: extends.md
        category: Tests
        parent: tests-index.html
        targets:
            - everything

    -   name: Hierarchy Demo
        category: Tests
        parent: tests-index.html
        template: template-hierarchy.html
        targets:
            - everything

    -   md: debug.md
        category: Tests
        parent: tests-index.html
        template: template-pdf.html
        targets:
            - everything

    -   name: Filters
        category: Filters
        section_header: true
        #parent: index.html
        html: filters-index.html
        template: landing.html
        targets:
            - everything
            - filterdemos

    -   md: filter-examples/badges.md
        #category: Filters
        #parent: filters-index.html
        targets:
            - everything
            - filterdemos
        #filters:
        #    - badges
        
    -   md: filter-examples/buttonize.md
        category: Filters
        parent: filters-index.html
        targets:
            - everything
            - filterdemos
        filters:
            - buttonize

    -   md: filter-examples/callouts.md
        parent: filters-index.html
        targets:
            - everything
            - filterdemos
        filters:
            - callouts


    #-   md: filter-examples/patriots.md
    #   html: filter-examples-patriots.html
    #     category: Filters
    #    parent: filters.html
    #    #targets:
    #        - everything
    #        - filterdemos
    #    filters:
    #        - patriots

    #-   md: filter-examples/patriots.md
    #    name: Custom Filter 2
    #    html: filter-examples-patriots2.html
    #    category: Filters
    #    parent: filters.html
    #    targets:
    #        - everything
    #        - filterdemos
    #    filters:
    #        - patriots2
    
    -   md: filter-examples/include_url.md
        category: Filters
        parent: filters-index.html
        targets:
            - everything
            - filterdemos
        filters:
            - include_url

    -   md: filter-examples/multicode_tabs.md
        category: Filters
        parent: filters-index.html
        targets:
            - everything
            - filterdemos
        filters:
            - multicode_tabs

    -   md: filter-examples/xrefs.md
        category: Filters
        parent: filters-index.html
        targets:
            - everything
            - filterdemos
        filters:
            - xrefs

# -------------------- Style Checker Rules ------------------------
word_substitutions_file: plainlanguage_words.yaml
phrase_substitutions_file: plainlanguage_phrases.yaml
